name = input("What is your name? ")
course = input("What course are you studying? ")
area = input("What aread of cybersecurity interests you? ")
print("Hello, " + name + "!")
print("You are studying " + course)
print("You are interested in " + area)